# Generated by Django 2.2.6 on 2019-11-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191104_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
