# Generated by Django 2.2.6 on 2019-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191104_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='StudentName',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
