# Generated by Django 2.2.6 on 2019-11-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADSL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsl_document',
            name='class_div',
        ),
        migrations.RemoveField(
            model_name='adsl_document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adsl_document',
            name='rollno',
        ),
    ]
