# Generated by Django 2.2.6 on 2019-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADSL', '0002_auto_20191103_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsl_abstract',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
